Repository openshift/knative-serving, pull requests merged in 2018-11, with the labels that each got.

#4 Fix SSH access for enabling admission webhooks in CI
  Makefile
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/build-image/entrypoint
  openshift/e2e-tests-openshift.sh
Labels: size/M

#9 Set `SSL_CERT_FILE` env variable for Knative Serving controller
  openshift/e2e-tests-openshift.sh
Labels: size/XS

#7 OWNER_ALIASES: Delete all users from Google, add QE + Engineering
  OWNERS
  OWNERS_ALIASES
Labels: size/L

#11 OWNERS, OWNER_ALIASES: Delete all users from Google, add QE + Enginee…
  OWNERS
  OWNERS_ALIASES
Labels: size/L

#13 Pull all images from the OpenShift internal registry
  openshift/e2e-tests-openshift.sh
  test/e2e/helloworld_shell_test.go
  test/util.go
Labels: approved, lgtm, size/M

#8 Knative Serving CI setup
  Makefile
  openshift/ci-operator/knative-images/activator/Dockerfile
  openshift/ci-operator/knative-images/autoscaler/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/queue/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/ci-operator/knative-test-images/autoscale/Dockerfile
  openshift/ci-operator/knative-test-images/controller/Dockerfile
  openshift/ci-operator/knative-test-images/envvars/Dockerfile
  openshift/ci-operator/knative-test-images/helloworld/Dockerfile
  openshift/ci-operator/knative-test-images/httpproxy/Dockerfile
  openshift/ci-operator/knative-test-images/pizzaplanetv1/Dockerfile
  openshift/ci-operator/knative-test-images/pizzaplanetv2/Dockerfile
  openshift/ci-operator/knative-test-images/singlethreaded/Dockerfile
  openshift/e2e-tests-openshift.sh
  test/e2e/helloworld_shell_test.go
  test/route.go
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, lgtm, size/L

#15 Resolve conflicts with upstream except OWNERS and OWNERS_ALIASES
  vendor/github.com/knative/pkg/test/e2e_flags.go
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, lgtm, size/XS
