Repository openshift/knative-serving, pull requests merged in 2019-05, with the labels that each got.

#102 new registry
  openshift/admission-webhooks.yaml
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#107 Force a build
  Makefile
  ci
Labels: approved, lgtm, size/XS

#110 Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#109 CatalogSource for 0.5.2 knative-serving
  openshift/olm/README.md
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/L

#113 Remove CRI-O bandaid.
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#115 Update Maistra to 0.10 - master
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#122 Install Serving using operator and use CI images.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/L

#124 Add new image.
  Makefile
  openshift/ci-operator/knative-images/certmanager/Dockerfile
Labels: approved, lgtm, size/XS

#125 Remove deleted image.
  openshift/ci-operator/knative-test-images/environment/Dockerfile
Labels: approved, lgtm, size/XS

#126 Install core binaries sequentially.
  Makefile
Labels: approved, lgtm, size/XS

#127 Skip 'TestShouldRunAsUserContainerDefault'.
  test/conformance/user_test.go
Labels: approved, lgtm, size/XS

#130 Disable sidecar injection as its broken on 4.1.
  openshift/e2e-tests-openshift.sh
  test/e2e/service_to_service_test.go
Labels: approved, lgtm, size/XS

#131 Update Maistra to 0.10 and disable sidecar injection for 0.5.2.
  openshift/e2e-tests-openshift.sh
  test/e2e/service_to_service_test.go
Labels: approved, lgtm, size/M

#132 Disable istio sidecar injection.
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#133 Align RBAC with upstream and add finalizers.
  openshift/release/knative-serving-v0.5.2.yaml
Labels: approved, size/S

#134 Don't explicitly install Istio
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/L

#135 Don't explicitly install Istio (master)
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/L

#105 Simplify resetting to upstream/master
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/S

#136 Removing unused var
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#137 Add a mechanism to provide patches that are carried over.
  openshift/patches/001-servicetoservice.patch
  openshift/patches/002-runaspid.patch
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/M

#128 Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#141 Cleaning up e2e tests script
  Makefile
  openshift/ci-operator/knative-test-images/controller/Dockerfile
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#142 Cleaning up e2e tests script
  Makefile
  openshift/ci-operator/knative-test-images/controller/Dockerfile
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#139 Knative Serving 0.6.0
  openshift/e2e-tests-openshift.sh
  openshift/olm/README.md
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/XXL
