Repository openshift/knative-serving, pull requests merged in 2019-08, with the labels that each got.

#208 Add autoscaler-hpa image.
  Makefile
  openshift/ci-operator/knative-images/autoscaler-hpa/Dockerfile
Labels: approved, lgtm, size/XS

#212 Update route retry patch
  openshift/patches/003-routeretry.patch
Labels: approved, lgtm, size/M

#215 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#219 Move olm namespace to openshift-marketplace after OpenShift 4.2
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#221 Update grpc patch to test without resolvabledomain option
  openshift/patches/004-grpc.patch
Labels: approved, lgtm, size/S

#222 Disable HPA autoscaling test.
  openshift/patches/005-disablehpa.patch
Labels: approved, lgtm, size/S

#226 Run our 0.7.1 release against a newer Maistra and Operator.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
  test/e2e/autoscale_test.go
Labels: approved, lgtm, size/L

#229 Test operator TP1-02 via the 0.7.1 CI.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/XL

#231 Bump the serverless operator's versions to TP1-03 with ingress 0.0.7.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/M
