Repository openshift/knative-serving, pull requests merged in 2019-10, with the labels that each got.

#265 Run upstream rolling upgrade tests
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/L

#266 Sync catalogsource with latest change in serverless-operator
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/S

#268 Add productization related files
  Makefile
  container.yaml
  content_sets.yml
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
  openshift/productization/generate-dockerfiles/gen_dockerfiles.sh
Labels: approved, lgtm, size/L

#269 Update k-s-o image in catalog source to v0.8.1-1.1.0-03
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/XS

#271 Fix productized build with change to WORKDIR
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
Labels: approved, lgtm, size/S

#272 Build our binaries with Golang 1.13.
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm, size/XS

#273 Update openshift ingress image.
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/XS

#274 Bump operator image to latest.
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, size/XS

#276 Bump CI.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/release/knative-serving-ci.yaml
  test/conformance/api/v1/errorcondition_test.go
  test/conformance/api/v1alpha1/errorcondition_test.go
  test/conformance/api/v1beta1/errorcondition_test.go
  test/e2e/destroypod_test.go
Labels: approved, lgtm, size/L

#281 Remove teardown process to enable log collection of Knative pods.
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#282 Make sure productization images look like ko built images.
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
Labels: approved, lgtm, size/M

#284 Bump YAML library version.
  Gopkg.lock
  Gopkg.toml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
Labels: approved, size/M

#285 Bump K-S-O and K-O-I references for CVE.
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, size/XS

#287 Bump YAML and operator versions on the 0.9 branch.
  Gopkg.lock
  Gopkg.toml
  openshift/olm/knative-serving.catalogsource.yaml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
Labels: approved, lgtm, size/M

#288 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#292 Expand 005-disablehpa.patch to skip hpa test for TestAutoscaleUpCountPods
  openshift/patches/005-disablehpa.patch
Labels: approved, lgtm, size/S

#291 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#300 Only locally override resolvable flag.
  openshift/patches/004-grpc.patch
Labels: approved, lgtm, size/S

#299 Only locally override resolvable flag.
  test/e2e/grpc_test.go
Labels: approved, lgtm, size/XS

#302 Update productization files for v0.9.0
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.networking-nscert
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
  openshift/productization/generate-dockerfiles/gen_dockerfiles.sh
Labels: approved, lgtm, size/L

#303 Use matching operator in CI.
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, size/XS

#306 Fix WORKDIR
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.networking-nscert
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
  openshift/productization/generate-dockerfiles/gen_dockerfiles.sh
Labels: approved, lgtm, size/M

#304 [CP] Improve prober error message (#5638)
  pkg/network/probe_handler_test.go
  pkg/network/prober/prober.go
  pkg/network/prober/prober_test.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
Labels: approved, lgtm, size/M
