Repository openshift/knative-serving, pull requests merged in 2019-07, with the labels that each got.

#173 Update ci config script
  openshift/ci-operator/generate-ci-config.sh
Labels: approved, lgtm, size/XS

#174 Resolve only v1alpha1 CRDs until we're on OpenShift 4.2.
  openshift/e2e-tests-openshift.sh
  openshift/patches/002-v1beta1.patch
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
Labels: approved, lgtm, size/M

#178 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#179 Updated knative-serving-operator image to v0.7.1
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/L

#181 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#182 Run tests with --resolvabledomain.
  openshift/e2e-tests-openshift.sh
  openshift/patches/001-servicetoservice.patch
  openshift/patches/003-routeretry.patch
  openshift/patches/004-grpc.patch
Labels: approved, lgtm, size/M

#185 Fix corrupt patch.
  openshift/patches/003-routeretry.patch
Labels: approved, lgtm, size/XS

#187 Cherry pics for v0.7.1 branch
  test/conformance/api/v1alpha1/generatename_test.go
  test/conformance/api/v1beta1/generatename_test.go
  test/conformance/runtime/header_test.go
  test/e2e/service_to_service_test.go
Labels: approved, lgtm, size/M

#190 Remove no longer applicable patch.
  openshift/patches/002-v1beta1.patch
Labels: approved, lgtm, size/S

#192 Remove some Dockerfile
  openshift/ci-operator/knative-test-images/bloatingcow/Dockerfile
  openshift/ci-operator/knative-test-images/printport/Dockerfile
  openshift/ci-operator/knative-test-images/protocols/Dockerfile
  openshift/ci-operator/knative-test-images/workingdir/Dockerfile
Labels: approved, lgtm, size/S

#193 Replace canonical_go_repository github.com/knative/serving with knative.dev/serving
  openshift/ci-operator/generate-ci-config.sh
Labels: approved, lgtm, size/XS

#194 Fix image reference search string to be knative.dev based.
  openshift/release/resolve.sh
Labels: approved, lgtm, size/S

#195 Update grpc patch to match upstream's updates.
  openshift/patches/004-grpc.patch
Labels: approved, lgtm, size/XS

#196 Remove obsolete release list in README
  README.md
Labels: approved, lgtm, size/XS

#188 Add format check of new branch name to pass for create-release-branch.sh
  openshift/release/create-release-branch.sh
Labels: approved, lgtm, size/S

#200 Collect openshift-ingress logs and routes
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#201 DO NOT MERGE: CI Debug PR
  ci
Labels: approved, size/XS

#202 Update the catalogsource for the newest image.
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/L

#207 Dump subscription state and catalog-operator's log when e2e test failed
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#206 Move catalogsource to the same namespace with subscription
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S
