Repository openshift/knative-serving, pull requests merged in 2019-06, with the labels that each got.

#146 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#143 Removed updating openshift internal registry information from configmap
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#147 Account for changed CRD kind
  openshift/e2e-tests-openshift.sh
  openshift/olm/README.md
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/XXL

#148 Account for changed CRD kind
  openshift/e2e-tests-openshift.sh
  openshift/olm/README.md
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/XXL

#145 Removed updating registry information from configmap
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#152 Fix location of the patch to apply to.
  openshift/patches/002-runaspid.patch
Labels: approved, lgtm, size/S

#155 Apply patch to the correct location.
  openshift/patches/002-runaspid.patch
Labels: approved, lgtm, size/XS

#156 Fix path to conformance tests
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#154 Add restricted endpoints backport to release.yaml (backport fix).
  openshift/release/knative-serving-v0.6.0.yaml
Labels: approved, lgtm, size/XS

#157 Fix patch for container default test.
  openshift/patches/002-runaspid.patch
Labels: approved, lgtm, size/XS

#158 Add anyuid scc to run TestShouldRunAsUserContainerDefault
  openshift/e2e-tests-openshift.sh
  openshift/patches/002-runaspid.patch
Labels: approved, lgtm, size/S

#162 Add uid 1000 to runtime-unprivileged's Dockerfile
  openshift/ci-operator/generate-dockerfiles.sh
  openshift/ci-operator/knative-test-images/runtime-unprivileged/Dockerfile
Labels: approved, lgtm, size/S

#163 Fix service-to-service patch.
  openshift/patches/001-servicetoservice.patch
Labels: approved, size/S

#167 Add UID 65532 to run all containers as non-root user
  openshift/ci-operator/Dockerfile.in
  openshift/ci-operator/generate-dockerfiles.sh
  openshift/ci-operator/knative-images/activator/Dockerfile
  openshift/ci-operator/knative-images/autoscaler/Dockerfile
  openshift/ci-operator/knative-images/certmanager/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/istio/Dockerfile
  openshift/ci-operator/knative-images/queue/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/ci-operator/knative-test-images/autoscale/Dockerfile
  openshift/ci-operator/knative-test-images/bloatingcow/Dockerfile
  openshift/ci-operator/knative-test-images/failing/Dockerfile
  openshift/ci-operator/knative-test-images/grpc-ping/Dockerfile
  openshift/ci-operator/knative-test-images/hellovolume/Dockerfile
  openshift/ci-operator/knative-test-images/helloworld/Dockerfile
  openshift/ci-operator/knative-test-images/httpproxy/Dockerfile
  openshift/ci-operator/knative-test-images/observed-concurrency/Dockerfile
  openshift/ci-operator/knative-test-images/pizzaplanetv1/Dockerfile
  openshift/ci-operator/knative-test-images/pizzaplanetv2/Dockerfile
  openshift/ci-operator/knative-test-images/printport/Dockerfile
  openshift/ci-operator/knative-test-images/protocols/Dockerfile
  openshift/ci-operator/knative-test-images/runtime/Dockerfile
  openshift/ci-operator/knative-test-images/singlethreaded/Dockerfile
  openshift/ci-operator/knative-test-images/timeout/Dockerfile
  openshift/ci-operator/knative-test-images/workingdir/Dockerfile
  openshift/ci-operator/knative-test-images/wsserver/Dockerfile
Labels: approved, lgtm, size/M

#165 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS
