Repository openshift/knative-serving, pull requests merged in 2019-04, with the labels that each got.

#47 OLM manifests, including CatalogSource
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/olm/knative-serving.crd.yaml
  openshift/olm/knative-serving.package.yaml
  openshift/olm/knative-serving.v0.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XXL

#49 Update with release images from downstream fork
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/olm/knative-serving.v0.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#48 Run v0.5.0 through CI.
  ci
Labels: approved, lgtm, size/XS

#51 Trigger CI to test auto merge of PRs from the webhook
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#50 Update openshift specific files.
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/olm/knative-serving.crd.yaml
  openshift/olm/knative-serving.package.yaml
  openshift/olm/knative-serving.v0.4.1.clusterserviceversion.yaml
  openshift/release/README.md
  openshift/release/create-release-branch.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/XXL

#53 Allow builds to be used in a kservice [SRVCOM-428]
  openshift/olm/knative-serving.v0.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#54 Generate release yaml with replaced image references
  Makefile
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-tests-openshift.sh
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/knative-serving-v0.4.1.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm, size/XL

#55 Generate release yaml for knative operator
  Makefile
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-tests-openshift.sh
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
Labels: approved, lgtm, size/M

#58 Enable the controller to use pipeline resources.
  openshift/olm/knative-serving.v0.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#56 Generate knative-serving-v0.5.0.yaml
  Makefile
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-tests-openshift.sh
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/knative-serving-v0.5.0.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm, size/XXL

#60 Apparently, the 'replaces' field must refer to a CSV within the CS
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/olm/knative-serving.v0.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#64 Update forked repo synching automation
  openshift/release/README.md
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/M

#71 Need extra perms for Operator checks
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/olm/knative-serving.v0.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test, size/M

#76 Add required perms to list ingresses
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/olm/knative-serving.v0.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#78 delete empty line per PR 76 comment
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/XS

#80 Updating openshift specific files.
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/olm/knative-serving.v0.4.1.clusterserviceversion.yaml
  openshift/release/README.md
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/L

#65 Update synch automation script again
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/XS

#81 Add the newly added networking controller to the images to build.
  Makefile
  openshift/ci-operator/knative-images/istio/Dockerfile
Labels: approved, lgtm, size/XS

#82 Generate knative-serving-ci.yaml for CI
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/S

#83 Poke the 0.5.1 CI.
  ci
Labels: approved, size/XS

#86 Release 0.5.1, using CS generated from new operator
  openshift/olm/README.md
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/olm/knative-serving.crd.yaml
  openshift/olm/knative-serving.package.yaml
  openshift/olm/knative-serving.v0.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XXL

#88 Debugging 0.5.1 failures.
  openshift/e2e-tests-openshift.sh
Labels: approved, size/XS

#89 Cherry pick e2e script fix.
  openshift/e2e-tests-openshift.sh
Labels: approved, size/XS

#90 Create alternative test namespace as well.
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#87 Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#91 Hopefully a fix for [SRVKS-82]
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/XS

#92 chore(olm): Added finalizer perms to Deployments in "apps" group, too.
  openshift/olm/knative-serving.catalogsource.yaml
Labels: ok-to-test, size/XS

#98 Don't resolve docker.io images.
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS
