Repository openshift/knative-serving, pull requests merged in 2019-03, with the labels that each got.

#31 Get knative 0.3 to pass on OpenShift 4.
  cmd/queue/main.go
  openshift/e2e-tests-openshift.sh
  test/e2e/helloworld_shell_test.go
  third_party/istio-1.0.2/istio.yaml
  third_party/istio-1.0.2/prestop-sleep.yaml.patch
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, lgtm, size/L

#33 Try using the Maistra operator for Istio
  config/202-gateway.yaml
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/L

#38 Pull in fixes from the 0.3 branch.
  cmd/queue/main.go
  config/202-gateway.yaml
  openshift/e2e-tests-openshift.sh
  test/e2e/helloworld_shell_test.go
  third_party/istio-1.0.2/istio.yaml
  third_party/istio-1.0.2/prestop-sleep.yaml.patch
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, lgtm, size/L

#39 Build with golang 1.12.
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm, size/XS

#42 Make release 0.4.1 work through CI.
  openshift/e2e-tests-openshift.sh
  test/conformance/cgroup_test.go
  test/e2e/websocket_test.go
Labels: approved, lgtm, size/M

#43 Pull fixes to scripts from the latest release.
  openshift/ci-operator/knative-test-images/grpc-ping/Dockerfile
  openshift/ci-operator/knative-test-images/hellovolume/Dockerfile
  openshift/ci-operator/knative-test-images/protocols/Dockerfile
  openshift/ci-operator/knative-test-images/runtime/Dockerfile
  openshift/ci-operator/knative-test-images/wsserver/Dockerfile
  openshift/e2e-tests-openshift.sh
Labels: approved, size/M

#44 Add script to automatically create and update release branches.
  openshift/release/README.md
  openshift/release/create-release-branch.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/M

#46 Run release-v0.4.1 through CI.
  ci
Labels: approved, lgtm, size/XS
