Repository openshift/knative-serving, pull requests merged in 2019-12, with the labels that each got.

#350 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, lgtm, size/XS

#353 More robust WaitForServiceLatestRevision function
  test/v1/revision.go
  test/v1/service.go
  test/v1alpha1/revision.go
  test/v1alpha1/service.go
  test/v1beta1/revision.go
  test/v1beta1/service.go
Labels: approved, area/test-and-release, lgtm, size/M

#359 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#361 Cherry picks from 0.10.1
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
  pkg/reconciler/route/resources/service.go
  pkg/reconciler/route/resources/service_test.go
  test/e2e/service_to_service_test.go
Labels: approved, area/test-and-release, lgtm, size/L

#360 Regenerate Dockerfiles using updated scripts
  openshift/productization/dist-git/Dockerfile.LActivator
  openshift/productization/dist-git/Dockerfile.LAutoscaler
  openshift/productization/dist-git/Dockerfile.LAutoscaler-HPA
  openshift/productization/dist-git/Dockerfile.LController
  openshift/productization/dist-git/Dockerfile.LNetworking-CertManager
  openshift/productization/dist-git/Dockerfile.LNetworking-Istio
  openshift/productization/dist-git/Dockerfile.LNetworking-NSCert
  openshift/productization/dist-git/Dockerfile.LQueue
  openshift/productization/dist-git/Dockerfile.LWebhook
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.networking-nscert
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
  openshift/productization/generate-dockerfiles/gen_dockerfiles.sh
Labels: size/L

#362 Bump version to v0.10.1
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.networking-nscert
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/gen_dockerfiles.sh
Labels: size/S
