Repository openshift/knative-serving, pull requests merged in 2019-09, with the labels that each got.

#243 Add nscert image
  Makefile
  openshift/ci-operator/knative-images/nscert/Dockerfile
Labels: approved, lgtm, size/XS

#244 Install ServiceMesh via operatorhub.
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#245 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#253 Fix create-release-branch script.
  openshift/release/create-release-branch.sh
Labels: approved, lgtm, size/XS

#254 Modified v1alpha1 to v1beta1
  Makefile
  openshift/ci-operator/knative-images/nscert/Dockerfile
  openshift/release/generate-release.sh
  openshift/release/knative-serving-ci.yaml
Labels: approved, lgtm, size/S

#255 Fix route retry patch.
  openshift/patches/003-routeretry.patch
Labels: approved, lgtm, size/M

#256 Install ServiceMesh operator, use aggregate operator.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/servicemesh/controlplane-install.yaml
  openshift/servicemesh/operator-install.yaml
Labels: approved, lgtm, size/XL

#260 Remove API specification from generate-release script.
  openshift/release/generate-release.sh
Labels: approved, lgtm, size/XS

#252 Add productization related files
  Makefile
  container.yaml
  content_sets.yml
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
  openshift/productization/generate-dockerfiles/gen_dockerfiles.sh
  openshift/release/create-release-branch.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm, needs-ok-to-test, size/L

#264 Update knative-serving-operator image
  openshift/olm/knative-serving.catalogsource.yaml
  test/conformance/api/v1alpha1/errorcondition_test.go
  test/conformance/api/v1beta1/errorcondition_test.go
Labels: approved, lgtm, size/M
