Repository openshift/knative-serving, pull requests merged in 2019-11, with the labels that each got.

#308 [CP] Skip tag uniqeness check for traffic targets without tags (#5583)
  pkg/apis/serving/v1/route_validation.go
  pkg/apis/serving/v1/route_validation_test.go
Labels: approved, lgtm, size/S

#309 Improve productization Dockerfile generation
  Makefile
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.networking-nscert
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
  openshift/productization/generate-dockerfiles/gen_dockerfiles.sh
  openshift/release/create-release-branch.sh
Labels: size/M

#316 Change maintainer to serverless-support@redhat.com
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.networking-nscert
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
Labels: size/S

#310 Improve productization Dockerfile generation on master
  Makefile
  openshift/productization/dist-git/.gitkeep
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
  openshift/productization/generate-dockerfiles/gen_dockerfiles.sh
  openshift/release/create-release-branch.sh
Labels: approved, lgtm, size/L

#313 Update catalogsource to include serverless-operator.v1.2.0 CSV
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/XL

#298 Adjust CI for auto-installing SMCP and SMMR.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/servicemesh/controlplane-install.yaml
Labels: approved, lgtm, size/L

#320 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#324 Update to the latest and greatest k-s-o and k-o-i versions.
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, size/XS

#328 Update operator versions and fix periodic CI.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/S

#336 CI changes to auto install service mesh for master branch
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/servicemesh/controlplane-install.yaml
  openshift/servicemesh/operator-install.yaml
Labels: approved, lgtm, size/L

#334 Rolling upgrade tests
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/servicemesh/controlplane-install.yaml
  test/v1/revision.go
  test/v1/service.go
  test/v1alpha1/revision.go
  test/v1alpha1/service.go
  test/v1beta1/revision.go
  test/v1beta1/service.go
Labels: approved, lgtm, size/L

#335 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, lgtm, size/XS

#338 Run conformance tests of all APIs.
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#340 Remove pod logs dump from e2e script
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#345 Define autoscaleSleep const with default value 500
  test/e2e/autoscale_test.go
Labels: approved, size/XS

#343 Backport imagetemplate mechanism.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/util.go
  vendor/knative.dev/pkg/test/e2e_flags.go
Labels: approved, lgtm, size/L

#347 Simplify the e2e tests script by pulling images from ci registry and adjust release creation.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm, size/L

#342 update k-s-o image and applied patches
  openshift/olm/knative-serving.catalogsource.yaml
  test/e2e/autoscale_test.go
  test/e2e/grpc_test.go
  test/v1/route.go
  test/v1alpha1/route.go
  test/v1beta1/route.go
Labels: approved, area/test-and-release, lgtm, size/M

#349 Backport image template.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/release/resolve.sh
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/util.go
  test/e2e/activator_test.go
  vendor/knative.dev/pkg/test/e2e_flags.go
Labels: approved, area/test-and-release, size/L
