Repository openshift/knative-serving, pull requests merged in 2020-02, with the labels that each got.

#390 Bump CI.
  ci
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, size/XS

#394 [CP] Clean up VirtualService and reconcile kingress when ingress.class annotation is update
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/reconcile_resources_test.go
Labels: approved, lgtm, size/L

#402 Replace all direct usages of the CI registry.
  openshift/ci-operator/Dockerfile.in
  openshift/ci-operator/knative-images/activator/Dockerfile
  openshift/ci-operator/knative-images/autoscaler-hpa/Dockerfile
  openshift/ci-operator/knative-images/autoscaler/Dockerfile
  openshift/ci-operator/knative-images/certmanager/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/istio/Dockerfile
  openshift/ci-operator/knative-images/nscert/Dockerfile
  openshift/ci-operator/knative-images/queue/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/ci-operator/knative-test-images/autoscale/Dockerfile
  openshift/ci-operator/knative-test-images/failing/Dockerfile
  openshift/ci-operator/knative-test-images/flaky/Dockerfile
  openshift/ci-operator/knative-test-images/grpc-ping/Dockerfile
  openshift/ci-operator/knative-test-images/hellovolume/Dockerfile
  openshift/ci-operator/knative-test-images/helloworld/Dockerfile
  openshift/ci-operator/knative-test-images/httpproxy/Dockerfile
  openshift/ci-operator/knative-test-images/observed-concurrency/Dockerfile
  openshift/ci-operator/knative-test-images/pizzaplanetv1/Dockerfile
  openshift/ci-operator/knative-test-images/pizzaplanetv2/Dockerfile
  openshift/ci-operator/knative-test-images/runtime/Dockerfile
  openshift/ci-operator/knative-test-images/singlethreaded/Dockerfile
  openshift/ci-operator/knative-test-images/timeout/Dockerfile
  openshift/ci-operator/knative-test-images/wsserver/Dockerfile
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/M

#401 Replace all direct usages of the CI registry.
  openshift/ci-operator/Dockerfile.in
  openshift/ci-operator/knative-images/activator/Dockerfile
  openshift/ci-operator/knative-images/autoscaler-hpa/Dockerfile
  openshift/ci-operator/knative-images/autoscaler/Dockerfile
  openshift/ci-operator/knative-images/certmanager/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/istio/Dockerfile
  openshift/ci-operator/knative-images/nscert/Dockerfile
  openshift/ci-operator/knative-images/queue/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/ci-operator/knative-test-images/autoscale/Dockerfile
  openshift/ci-operator/knative-test-images/failing/Dockerfile
  openshift/ci-operator/knative-test-images/grpc-ping/Dockerfile
  openshift/ci-operator/knative-test-images/hellovolume/Dockerfile
  openshift/ci-operator/knative-test-images/helloworld/Dockerfile
  openshift/ci-operator/knative-test-images/httpproxy/Dockerfile
  openshift/ci-operator/knative-test-images/observed-concurrency/Dockerfile
  openshift/ci-operator/knative-test-images/pizzaplanetv1/Dockerfile
  openshift/ci-operator/knative-test-images/pizzaplanetv2/Dockerfile
  openshift/ci-operator/knative-test-images/runtime/Dockerfile
  openshift/ci-operator/knative-test-images/singlethreaded/Dockerfile
  openshift/ci-operator/knative-test-images/timeout/Dockerfile
  openshift/ci-operator/knative-test-images/wsserver/Dockerfile
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, size/M

#404 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, lgtm, size/XS
