Repository openshift/knative-serving, pull requests merged in 2020-10, with the labels that each got.

#565 Fix 001-object.patch
  openshift/patches/001-object.patch
Labels: approved, lgtm

#568 Add test image of multicontainer's code directories
  Makefile
Labels: approved, lgtm

#571 Use the serverless-operator v1.10.0 to do our testing for now
  openshift/olm/config_map.patch
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved

#569 [RELEASE-v0.17.3] Reconcile Ingress when label was different from desired
  pkg/reconciler/route/reconcile_resources.go
  pkg/reconciler/route/table_test.go
Labels: approved, lgtm

#570 [SRVKS-644] Add more migration logic, fix nilpointers, enhance logging
  pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/revision/reconcile_resources.go
Labels: approved, lgtm

#573 Install yq and httpd-tools in base image
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#574 Fix gRPC patch
  openshift/patches/004-grpc.patch
Labels: approved, lgtm

#575 Fix 003-routeretry.patch
  openshift/patches/003-routeretry.patch
Labels: approved, lgtm

#576 Update CSV with new bundle format
  openshift/config_map.patch
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
  openshift/olm/README.md
  openshift/olm/catalog.sh
  openshift/olm/config_map.patch
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/olm/minimum.package.yaml
Labels: approved, lgtm

#579 Disable HA autoscaler test until operator support it
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#567 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, do-not-merge/invalid-owners-file, kind/sync-fork-to-upstream

#580 Add new feature tests
  openshift/e2e-common.sh
Labels: approved, lgtm
