Repository openshift/knative-serving, pull requests merged in 2020-03, with the labels that each got.

#407 Fix 003-routeretry.patch patch
  openshift/patches/003-routeretry.patch
Labels: approved, lgtm, size/S

#410 Remving myself from approvers/reviewers
  OWNERS_ALIASES
Labels: approved, size/S

#405 Make WaitForConfigLatestRevision more robust (#6979)
  test/conformance/api/v1/generatename_test.go
  test/conformance/api/v1/route_test.go
  test/conformance/api/v1alpha1/generatename_test.go
  test/conformance/api/v1alpha1/route_test.go
  test/conformance/api/v1beta1/generatename_test.go
  test/conformance/api/v1beta1/route_test.go
  test/v1/configuration.go
  test/v1/route.go
  test/v1alpha1/configuration.go
  test/v1alpha1/route.go
  test/v1beta1/configuration.go
  test/v1beta1/route.go
Labels: approved, area/test-and-release, lgtm, size/L

#412 Bump servleress-operator to v1.5.0 and remove istio
  Makefile
  openshift/ci-operator/knative-images/istio/Dockerfile
  openshift/e2e-tests-openshift.sh
  openshift/olm/config_map.patch
  openshift/olm/generate.sh
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm, size/XXL

#414 [SRVKS-316] Use buildflag to workaround gcp behavior.
  Makefile
  openshift/productization/generate-dockerfiles/Dockerfile.in
Labels: approved, lgtm, size/XS

#421 Kick CI.
  ci
Labels: approved

#422 Remove all keychain plugins.
  Makefile
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.networking-nscert
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
Labels: approved

#425 Update GOFLAGS tags to use comma separated instead of space separated
  Makefile
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.networking-nscert
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
Labels: approved, lgtm
