Repository openshift/knative-serving, pull requests merged in 2020-04, with the labels that each got.

#436 Update gRPC patch
  openshift/patches/004-grpc.patch
Labels: approved, lgtm

#439 updates catalogsource and channel
  openshift/e2e-tests-openshift.sh
  openshift/olm/config_map.patch
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm

#440 [SRVKS-227] Completely disable prometheus exporter endpoints.
  openshift/olm/knative-serving.catalogsource.yaml
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
Labels: approved

#443 Kick CI.
  ci
Labels: approved

#447 Removing myself from owners/reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#446 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#445 Reconcile on all private service events in KPA. (#7514)
  pkg/reconciler/autoscaling/kpa/controller.go
Labels: approved, lgtm

#448 Enhance routeretry patch
  openshift/patches/003-routeretry.patch
Labels: approved, lgtm

#450 Enhance retrying route 0.13.2
  openshift/patches/003-routeretry.patch
  test/v1/route.go
  test/v1alpha1/route.go
  test/v1beta1/route.go
Labels: approved, area/test-and-release, lgtm

#458 [BACKPORT] Propagate Ingress status once ObservedGenerated matches generation.
  pkg/reconciler/route/route.go
  pkg/reconciler/route/table_test.go
  pkg/testing/functional.go
  pkg/testing/v1/route.go
Labels: approved, area/test-and-release

#455 [SRVKS-472, SRVKS-473, SRVKS-470] HA tests for autoscaler-hpa, controller, activator
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-serving.catalogsource.yaml
  pkg/testing/v1/service.go
  test/e2e-tests.sh
  test/ha/activator_test.go
  test/ha/autoscalerhpa_test.go
  test/ha/controller_test.go
  test/ha/ha.go
Labels: approved, area/test-and-release

#461 Rename TestServiceToServiceCallViaActivator TestSvcToSvcViaActivator
  test/e2e/service_to_service_test.go
Labels: approved, area/test-and-release, lgtm
