Repository openshift/knative-serving, pull requests merged in 2020-07, with the labels that each got.

#496 Add a patch to fix the failing logging test.
  openshift/patches/005-loggingtest.patch
Labels: approved, lgtm

#499 Remove a patch for TestRequestLogs
  openshift/patches/005-loggingtest.patch
Labels: approved, lgtm

#490 Produce knative-serving-src image
  Makefile
  openshift/ci-operator/source-image/Dockerfile
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#502 Add replica option to HA tests
  openshift/e2e-common.sh
Labels: approved, lgtm

#503 Update operator and Kourier version to 0.14
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm

#492 Improve dev experience
  Makefile
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#504 Change the name of variables to avoid override upstream's readonly variables
  openshift/e2e-common.sh
Labels: approved, lgtm

#501 [BACKPORT] Make upgrade prober configurable re: SLO. (#8448)
  test/upgrade/probe_test.go
Labels: approved, area/test-and-release, lgtm

#505 Kick CI.
  ci
  openshift/e2e-common.sh
Labels: approved

#508 Add wait_for_leader_controller to our scripts and exit early.
  openshift/e2e-common.sh
Labels: approved, lgtm

#510 Add wait_for_leader_controller to our scripts and exit early.
  openshift/e2e-common.sh
Labels: approved

#515 Collect Knative specific log by must-gather instead of upstream's dump script
  openshift/e2e-common.sh
  openshift/e2e-tests-local.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#516 [RELEASE-v0.15.2] Add storage-version-migration image.
  Makefile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/e2e-common.sh
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved

#519 Add storage-version-migration image.
  Makefile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/e2e-common.sh
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm

#518 [RELEASE-v0.16.0] Add storage-version-migration image.
  Makefile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/e2e-common.sh
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm

#520 Add patch for TestServiceValidationWithInvalidPodSpec
  openshift/patches/005-dryrun.patch
Labels: approved, lgtm

#521 Enable allow-zero-initial-scale in config-autoscaler
  openshift/e2e-common.sh
  openshift/release/resolve.sh
Labels: approved, lgtm

#523 Fix TestRequestLogs by adding observability config
  openshift/e2e-common.sh
Labels: approved, lgtm
