Repository openshift/knative-serving, pull requests merged in 2020-09, with the labels that each got.

#541 Print indexes of invalid responses in conformance tests
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/util.go
Labels: approved, area/test-and-release, lgtm

#542 Fix gRPC patch after k8s lib to 1.18
  openshift/patches/004-grpc.patch
Labels: approved, lgtm

#544 Fix gRPC patch
  openshift/patches/004-grpc.patch
Labels: approved, lgtm

#546 Throttle CheckDistribution in conformance. - release-v0.16.0
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/util.go
Labels: approved, area/test-and-release, lgtm

#545 Throttle CheckDistribution in conformance - release-v0.15.2
  test/conformance/api/v1/util.go
  test/conformance/api/v1alpha1/util.go
  test/conformance/api/v1beta1/util.go
Labels: approved, area/test-and-release, lgtm

#549 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#554 [RELEASE-v0.17.3] Add ImageCache CRD link
  config/core/300-imagecache.yaml
  openshift/release/knative-serving-ci.yaml
  openshift/release/knative-serving-v0.17.3.yaml
Labels: approved, lgtm
