Repository openshift/knative-serving, pull requests merged in 2020-01, with the labels that each got.

#368 Trigger CI to trigger promotion.
  ci
Labels: approved, lgtm

#371 Prefix the VERSION string with v
  openshift/productization/generate-dockerfiles/gen_dockerfiles.sh
Labels: approved, lgtm, size/XS

#370 Prefix the VERSION string with v
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.networking-nscert
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/gen_dockerfiles.sh
Labels: approved, lgtm, size/S

#376 Update master version of Dockerfile.in
  openshift/productization/generate-dockerfiles/Dockerfile.in
Labels: approved, lgtm, size/XS

#377 Update p12n Dockerfiles
  openshift/productization/dist-git/Dockerfile.activator
  openshift/productization/dist-git/Dockerfile.autoscaler
  openshift/productization/dist-git/Dockerfile.autoscaler-hpa
  openshift/productization/dist-git/Dockerfile.controller
  openshift/productization/dist-git/Dockerfile.networking-certmanager
  openshift/productization/dist-git/Dockerfile.networking-istio
  openshift/productization/dist-git/Dockerfile.networking-nscert
  openshift/productization/dist-git/Dockerfile.queue
  openshift/productization/dist-git/Dockerfile.webhook
  openshift/productization/generate-dockerfiles/Dockerfile.in
Labels: approved, lgtm, size/M

#380 Fix release branch script to allow for multi-digit versions.
  openshift/release/create-release-branch.sh
Labels: approved, lgtm, size/XS

#379 Bump CI.
  ci
Labels: approved, lgtm, size/XS
