Repository openshift/knative-serving, pull requests merged in 2020-12, with the labels that each got.

#601 Use empty OPENSHIFT_CI variable to keep original serverless images
  openshift/e2e-common.sh
Labels: approved, lgtm

#602 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream

#603 Add Dockerfile to build domain-mapping and domain-mapping-webhook images
  Makefile
  openshift/ci-operator/knative-images/domain-mapping-webhook/Dockerfile
  openshift/ci-operator/knative-images/domain-mapping/Dockerfile
Labels: approved, lgtm

#605 Apply carried patches
  test/e2e/grpc_test.go
  test/e2e/service_validation_test.go
  test/v1/route.go
  vendor/knative.dev/pkg/test/helpers/name.go
Labels: area/test-and-release

#607 Kick CI
  ci
  test/e2e/autoscale.go
  test/e2e/autoscale_test.go
  test/ha/autoscaler_test.go
Labels: area/test-and-release

#612 [0.19] Backport https://github.com/knative/pkg/pull/1963
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, lgtm, needs-ok-to-test

#624 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream
