Repository openshift/knative-serving, pull requests merged in 2021-11, with the labels that each got.

#967 Bump release label to 0.26.0
  openshift/release/resolve.sh
Labels: lgtm, approved

#968 Use 0.26 release manifests
  openshift/release/knative-serving-ci.yaml
  openshift/release/knative-serving-v0.26.0.yaml
  openshift/release/resolve.sh
Labels: approved

#976 Build Serving images with Golang 1.17
  openshift/ci-operator/build-image/Dockerfile
Labels: lgtm, approved

#975 [RELEASE-v0.26.0] Build Serving images with Golang 1.17
  openshift/ci-operator/build-image/Dockerfile
Labels: lgtm, approved

#980 [RELEASE-v0.26.0] Fix TestRouteCreation to be consistent
  test/conformance/api/v1/route_test.go
Labels: lgtm, approved, area/test-and-release

#982 Remove ansible
  openshift/ci-operator/build-image/Dockerfile
Labels: lgtm, approved

#983 Fix route retry patch
  openshift/patches/003-routeretry.patch
Labels: lgtm, approved

#987 Fix 004-grpc.patch
  openshift/patches/004-grpc.patch
Labels: lgtm, approved
