Repository openshift/knative-serving, pull requests merged in 2021-07, with the labels that each got.

#831 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#835 [SRVKS-776] Allow for both probe-period and probe-timeout
  cmd/queue/main.go
  openshift/e2e-common.sh
Labels: approved, lgtm

#837 Use images as built onto the environment
  openshift/e2e-common.sh
Labels: approved, lgtm

#836 [CP][0.23]Add root ca for Controller HA test with https (#11471)
  openshift/release/knative-serving-ci.yaml
  openshift/release/knative-serving-v0.23.1.yaml
  openshift/release/resolve.sh
  test/ha/controller_test.go
Labels: approved, area/test-and-release, lgtm

#844 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#847 Update file path for ytt
  openshift/e2e-common.sh
Labels: approved, lgtm
