Repository openshift/knative-serving, pull requests merged in 2021-06, with the labels that each got.

#788 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#790 [main] mute noisy metrics patch
  openshift/patches/002-mutemetrics.patch
Labels: approved, lgtm

#796 Add a check for an existing sync PR in the midstream repo
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#798 Fix condition in update-to-head script
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#799 Do not fail update-to-head if there are not PRs
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#802 [BACKPORT][0.22.0] Fix websocket test with https option
  test/e2e/grpc_test.go
  test/e2e/websocket.go
  test/e2e/websocket_test.go
  test/util.go
Labels: approved, area/test-and-release, lgtm

#806 [SRVKS-756][CP][0.22] Use UID rather than label to avoid hitting character limits (#11360)
  pkg/apis/serving/register.go
  pkg/reconciler/domainmapping/resources/certificate.go
  pkg/reconciler/domainmapping/resources/certificate_test.go
  pkg/reconciler/domainmapping/resources/ingress.go
  pkg/reconciler/domainmapping/resources/ingress_test.go
  pkg/reconciler/domainmapping/table_test.go
Labels: approved, lgtm

#805 [CP][0.22] Add https option to activator ha test
  test/ha/activator_test.go
  test/ha/ha.go
Labels: approved, area/test-and-release, lgtm

#809 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#810 Remove unused ingress-class frag
  openshift/e2e-common.sh
Labels: approved, lgtm

#815 [CP][0.22] Add root ca for Controller HA test with https (#11471)
  test/ha/controller_test.go
Labels: approved, area/test-and-release, lgtm

#816 Use golang 1.15 image from registry to avoid docker rate limiting
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#817 Toggle autocreateClusterDomainClaims before test
  openshift/e2e-common.sh
Labels: approved, lgtm

#818 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#822 [CP][0.22] Use pkgtest.WaitForEndpointState in TestDomainMapping (#11537)
  test/conformance/api/v1alpha1/domain_mapping_test.go
Labels: approved, area/test-and-release, lgtm

#823 [CP][0.23] Use pkgtest.WaitForEndpointState in TestDomainMapping (#11537)
  test/conformance/api/v1alpha1/domain_mapping_test.go
Labels: approved, area/test-and-release, lgtm

#827 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#829 Remove scaling of machines
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
Labels: approved, lgtm

#833 Add v0.23 label to manifests
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
Labels: approved, lgtm

#832 [WIP][TESTONLY] Do not modify release label
  openshift/release/generate-release.sh
  openshift/release/knative-serving-ci.yaml
  openshift/release/resolve.sh
Labels: do-not-merge/work-in-progress
