Repository openshift/knative-serving, pull requests merged in 2021-03, with the labels that each got.

#668 [Release 0.20] Backport Unregister views to avoid slow oom issue during meter cleanup
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/modules.txt
Labels: approved, lgtm

#670 Fix race condition with Prober logger in upgrade tests
  test/upgrade/probe.go
Labels: approved, area/test-and-release, lgtm

#683 Use registry.ci.openshift.org and add serving.knative.dev/release label to manifest
  openshift/config_map.patch
  openshift/e2e-common.sh
  openshift/release/resolve.sh
Labels: approved, lgtm

#690 Make the scripts use main instead of master
  README.md
  openshift/release/create-release-branch.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#691 Pull in main from upstream
  openshift/release/README.md
  openshift/release/update-to-head.sh
Labels: approved

#705 Use knative-serving-v0.20.0.yaml for v0.20.0 branch
  openshift/config_map.patch
  openshift/e2e-common.sh
  openshift/release/knative-serving-v0.20.0.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm

#703 Assorted cherry-picks to fix activator bug and improve cold-start latency
  cmd/queue/execprobe.go
  cmd/queue/main.go
  pkg/activator/handler/concurrency_reporter.go
  pkg/activator/handler/concurrency_reporter_test.go
  pkg/reconciler/revision/resources/deploy_test.go
  pkg/reconciler/revision/resources/queue.go
  pkg/reconciler/revision/resources/queue_test.go
Labels: approved, lgtm

#706 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#713 Disable repo_gpgcheck for kube repo in build image
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved, lgtm
