Repository openshift/knative-serving, pull requests merged in 2022-05, with the labels that each got.

#1110 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: lgtm, approved, kind/sync-fork-to-upstream

#1116 Add automated branch cut script
  RELEASE.md
  openshift/release/create-release-branch.sh
  openshift/release/mirror-upstream-branches.sh
  openshift/release/update-to-head.sh
Labels: lgtm, approved

#1122 Add 0-kourier.yaml and 1-config-network.yaml to kourier.yaml
  openshift/e2e-common.sh
Labels: lgtm, approved, do-not-merge/hold

#1121 [RELEASE-v1.4] Add `vendor/knative.dev/pkg/test/spoof/openshift_checks.go`
  vendor/knative.dev/pkg/test/spoof/openshift_checks.go
Labels: lgtm, approved

#1119 Add git add in `openshift/release/create-release-branch.sh`
  openshift/release/create-release-branch.sh
Labels: lgtm, approved

#1123 Add `update-ci` to generate ci configs automatically
  Makefile
  RELEASE.md
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
  openshift/tui-functions.sh
Labels: lgtm, approved
