Repository openshift/knative-serving, pull requests merged in 2022-09, with the labels that each got.

#1226 [RELEASE-v1.4] Make QueueServingTLSPort optional
  cmd/queue/main.go
Labels: lgtm, approved

#1233 [release-v1.4] Tests for encryption with Kourier local gateway (#13263)
  .github/workflows/kind-e2e.yaml
  test/config/tls/cert-secret.yaml
  test/config/tls/generate.sh
  test/e2e-common.sh
  test/e2e/service_to_service_test.go
  test/test_images/httpproxy/httpproxy.go
Labels: lgtm, approved, area/test-and-release

#1230 Add runAsNonRoot patch to Kourier
  openshift/patches/007-kourier-nonroot.patch
Labels: lgtm, approved

#1239 Update update-ci.sh
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
Labels: lgtm, approved

#1236 [release-v1.5] Support config to deploy internal certificates automatically
  .github/workflows/kind-e2e.yaml
  Makefile
  cmd/activator/main.go
  cmd/controller/main.go
  cmd/queue/main.go
  config/core/300-secret.yaml
  go.mod
  go.sum
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
  openshift/release/artifacts/2-serving-core.yaml
  openshift/release/download_release_artifacts.sh
  openshift/release/knative-serving-ci.yaml
  openshift/release/manifest-patches/004-internal-tls.patch
  pkg/networking/constants.go
  pkg/reconciler/autoscaling/config/store_test.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/revision/cruds.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/resources/deploy.go
  pkg/reconciler/revision/revision.go
  pkg/reconciler/route/resources/ingress.go
  pkg/reconciler/route/resources/ingress_test.go
  test/config/tls/cert-secret.yaml
  test/config/tls/generate.sh
  test/e2e-common.sh
  test/e2e/autoscale_test.go
  test/e2e/service_to_service_test.go
  test/generate-cert.sh
  test/ha/ha.go
  test/test_images/httpproxy/httpproxy.go
  third_party/VENDOR-LICENSE/knative.dev/control-protocol/pkg/certificates/LICENSE
  vendor/knative.dev/control-protocol/LICENSE
  vendor/knative.dev/control-protocol/pkg/certificates/certs.go
  vendor/knative.dev/control-protocol/pkg/certificates/constants.go
  vendor/knative.dev/control-protocol/pkg/certificates/key_pair.go
  vendor/knative.dev/control-protocol/pkg/certificates/reconciler/certificates.go
  vendor/knative.dev/control-protocol/pkg/certificates/reconciler/controller.go
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/state.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: lgtm, approved, area/test-and-release

#1235 [release-v1.6] Tests for encryption with Kourier local gateway
  .github/workflows/kind-e2e.yaml
  Makefile
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
  openshift/e2e-common.sh
  openshift/e2e-tests.sh
  test/config/tls/cert-secret.yaml
  test/config/tls/generate.sh
  test/e2e-common.sh
  test/e2e/service_to_service_test.go
  test/test_images/httpproxy/httpproxy.go
Labels: lgtm, approved, area/test-and-release

#1242 [release-v1.4][SRVKS-961] Reset drainer to avoid deadlock when liveness probe fails
  cmd/queue/main.go
  test/test_images/readiness/service.yaml
  vendor/knative.dev/pkg/network/handlers/drain.go
Labels: lgtm, approved, area/test-and-release

#1244 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1237 [main] Tests for encryption with Kourier local gateway
  openshift/e2e-common.sh
Labels: lgtm, approved

#1245 [RELEASE-v1.7] revision request start timeout should default to revision timeout second (#13256)
  config/core/configmaps/defaults.yaml
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
Labels: lgtm, approved

#1234 [release-v1.7] Tests for encryption with Kourier local gateway
  .github/workflows/kind-e2e.yaml
  openshift/e2e-common.sh
  test/config/tls/cert-secret.yaml
  test/config/tls/generate.sh
  test/e2e-common.sh
  test/e2e/service_to_service_test.go
  test/test_images/httpproxy/httpproxy.go
Labels: lgtm, approved, area/test-and-release

#1252 [RELEASE-1.5] Reset drainer to avoid deadlock when liveness probe fails
  cmd/queue/main.go
  test/test_images/readiness/service.yaml
  vendor/knative.dev/pkg/network/handlers/drain.go
Labels: lgtm, approved, area/test-and-release

#1170 Use ubi8-minimal in ko builds
  openshift/patches/100-ko-baseimage.patch
Labels: lgtm, approved

#1255 [RELEASE-1.25] Fix checksum for configmap networking
  openshift/release/artifacts/2-serving-core.yaml
Labels: lgtm, approved

#1259 Fix Kourier patch
  openshift/patches/007-kourier-nonroot.patch
Labels: lgtm, approved

#1260 [MAIN] Workaround for activator's websocket disconnection
  openshift/e2e-common.sh
Labels: lgtm, approved
