Repository openshift/knative-serving, pull requests merged in 2022-03, with the labels that each got.

#1065 Bump version label to adopt operator CR v1.1
  openshift/release/resolve.sh
Labels: lgtm, approved

#1072 Add skip-cleanup-on-fail flag
  openshift/e2e-common.sh
Labels: lgtm, approved

#1070 [release-v1.1.2] Fix label in manifest on 1.1 branch
  openshift/e2e-common.sh
  openshift/release/knative-serving-ci.yaml
  openshift/release/knative-serving-knative-v1.1.2.yaml
  openshift/release/resolve.sh
  test/cleanup.go
  test/e2e_flags.go
Labels: lgtm, approved, area/test-and-release

#1073 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: lgtm, approved, kind/sync-fork-to-upstream

#1076 Run pvc test
  openshift/e2e-common.sh
Labels: lgtm, approved
