Repository openshift/knative-serving, pull requests merged in 2022-10, with the labels that each got.

#1265 [MAIN] Fix knative operator deployment name
  openshift/e2e-common.sh
Labels: lgtm, approved

#1270 Fix min version patch
  openshift/patches/005-k8s-min.patch
Labels: lgtm, approved

#1266 Verify serving installation before enabling TLS
  openshift/e2e-common.sh
Labels: lgtm, approved

#1275 Revert the autoscaling API version change
  openshift/release/update-to-head.sh
Labels: lgtm, approved

#1277 Drop seccomp from manifest for CI
  openshift/release/resolve.sh
Labels: lgtm, approved

#1273 [RELEASE-1.5] Fix tls patch
  openshift/release/manifest-patches/004-internal-tls.patch
Labels: lgtm, approved

#1279 Revert after commit
  openshift/release/update-to-head.sh
Labels: lgtm, approved

#1280 [MAIN] Fix kourier patch
  openshift/patches/007-kourier-nonroot.patch
  openshift/patches/007-kourier-nonseccomp.patch
Labels: approved

#1287 Fix 1.25 issues
  openshift/patches/008-remove-seccomp-queue.patch
  openshift/release/update-to-head.sh
Labels: approved

#1284 [RELEASE-1.5][BACKPORT] Allow setting seccompProfile to enable using restricted security profile
  config/core/configmaps/features.yaml
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
Labels: lgtm, approved

#1272 [RELEASE-1.5] [BACKPORT] Fix sc for psp compliance
  config/core/deployments/activator.yaml
  config/core/deployments/autoscaler.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/domainmapping-controller.yaml
  config/core/deployments/domainmapping-webhook.yaml
  config/core/deployments/webhook.yaml
  config/hpa-autoscaling/controller.yaml
  config/post-install/default-domain.yaml
  config/post-install/storage-version-migration.yaml
  openshift/release/artifacts/2-serving-core.yaml
  openshift/release/download_release_artifacts.sh
  openshift/release/knative-serving-ci.yaml
  openshift/release/knative-serving-knative-v1.5.0.yaml
  openshift/release/manifest-patches/005-psp.patch
  third_party/cert-manager-latest/cert-manager.yaml
  third_party/cert-manager-latest/net-certmanager.yaml
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: lgtm, approved

#1288 Fix corrupt patch
  openshift/patches/008-remove-seccomp-queue.patch
Labels: approved

#1291 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1283 RELEASE 1.5][BACKPORT] Run queue proxy with restricted profile
  pkg/reconciler/revision/resources/queue.go
Labels: lgtm, approved

#1290 Remove PodDisruptionBudget patch as we now support k8s 1.21+ / OCP 4.8+
  openshift/patches/006-pdb.patch
Labels: lgtm, approved

#1282 [RELEASE-1.5] [BACKPORT] Feature: Let users set allowPrivilegeEscalation
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  hack/schemapatch-config.yaml
  openshift/release/artifacts/2-serving-core.yaml
  openshift/release/knative-serving-ci.yaml
  openshift/release/knative-serving-knative-v1.5.0.yaml
  openshift/release/manifest-patches/005-psp.patch
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
Labels: lgtm, approved, area/test-and-release
